fit dark mode
halo-dev/plugin-search-widget pull request #12
Opened 2023-08-29 05:55 UTC by Dacong-wu

add a new div to fit the dark mode

2023-08-30 07:18 UTC, Dacong-wu commented
/assign @guqing

2023-08-30 08:02 UTC, ruibaby commented
几个问题：

1. 没有适配完全，比如输入的文字无法正常显示和界面圆角。

	<img width="667" alt="image" src="https://github.com/halo-sigs/plugin-search-widget/assets/21301288/84435536-ff49-4358-b8c2-bde9f82e4f81">

2. 单纯使用媒体查询的方式可能无法满足需求，并不是所有的主题都是完全使用媒体查询，很可能是单独通过 JS 控制。这就可能造成用户设备是 Dark Mode、网站本身是亮色主题，但是搜索框是 Dark Mode。

2023-08-30 08:17 UTC, Dacong-wu commented
1.这个问题我注意到了，新的已经修复完成了
2.我当时忘记考虑手动切换的场景，目前新的已经支持了，但是我仅仅是考虑了官方的通过tailwindcss dark mode class  这种方案，但是正如你说的，有的主题他的深色方案会有差异，这确实是一个问题
3.我是在官方案列中体验的时候发现，暗色主题下，他不适配，觉得很不应该这样所以提了这个Pr，但是如果要适配多主题，确实是一个问题

2023-09-01 06:45 UTC, ruibaby requested changes

2023-09-01 06:45 UTC, ruibaby commented on packages/search-widget/src/components/SearchWidget.vue
> +});
这种获取方式应该还是满足不了主题适配的需求，主题实现颜色切换的方案实在太多，所以最好的方式应该是和评论组件一样，支持传入变量。

https://github.com/halo-sigs/plugin-comment-widget?tab=readme-ov-file#%E4%B8%BB%E9%A2%98%E9%80%82%E9%85%8D

但这也涉及到一个问题，目前这个插件并没有初始化的过程，只有一个 API：`SearchWidget.open() `

2023-09-01 06:59 UTC, Dacong-wu commented on packages/search-widget/src/components/SearchWidget.vue
> +});
主题适配的问题，确认很麻烦。
我现在只是去解决了在你们默认主题下，这种不适配问题。
你说的评论插件这种方式，还是要主题去适配他，还不是他适配主题
刚刚我去手动切换了，貌似评论插件没有做出适配
![image](https://github.com/halo-sigs/plugin-search-widget/assets/62319007/fdad9e89-b785-4e15-92da-5ce77ffc83d8)

2023-09-01 07:03 UTC, ruibaby commented on packages/search-widget/src/components/SearchWidget.vue
> +});
应该是因为目前没有监听模式的变动，切换模式之后需要刷新页面才生效。此 PR 的改动应该也会有这个问题，主题就算切换了 html 的 class，组件也不会实时更改颜色。

2023-09-01 07:09 UTC, Dacong-wu commented on packages/search-widget/src/components/SearchWidget.vue
> +});
但是这个搜索框，你们做的是全屏的，打开他，你就没办法点图标去切换主题了不了🤣🤣

2023-09-01 07:13 UTC, ruibaby commented on packages/search-widget/src/components/SearchWidget.vue
> +});
说的好像很有道理，可以暂时使用这个 html class 的方案吧。但是建议直接在 https://github.com/halo-sigs/plugin-search-widget/blob/main/packages/search-widget/tailwind.config.cjs 配置 darkMode 为 `class`，不需要根据 `vElementClass` 一个一个去判断，直接 `dark:bg-xxx`。

2023-09-01 07:21 UTC, Dacong-wu commented on packages/search-widget/src/components/SearchWidget.vue
> +});
我开始这么做了，但是没有效果呀🤣
插件不是以shadow dom的形式插入的嘛
在shadow dom中它找不到html 的 class吧🤣，我这么理解没有错吧

2023-09-01 07:37 UTC, ruibaby commented on packages/search-widget/src/components/SearchWidget.vue
> +});
在最外层的 div 加上 class="dark or light" 就行了。

2023-09-17 14:38 UTC, closed without merging