add:extract more CSS variables
halo-dev/plugin-search-widget pull request #25
Opened 2024-02-19 06:05 UTC by jiewenhuang

为了更好的适配主题样式，新增以下CSS变量：
```css
--halo-search-widget-font-size-search-form-input:;                     /*输入框字体大小*/
--halo-search-widget-line-height-search-form-input:;                   /*输入框行高*/
--halo-search-widget-font-size-search-form-result-item-title:;         /*搜索结果项标题字体大小*/
--halo-search-widget-line-height-search-form-result-item-title:;       /*搜索结果项标题行高*/
--halo-search-widget-font-size-search-form-result-item-content:;       /*搜索结果项内容字体大小*/
--halo-search-widget-line-height-search-form-result-item-content:;     /*搜索结果项内容行高*/
--halo-search-widget-font-size-search-form-empty:;                     /*搜索结果为空时的字体大小*/
--halo-search-widget-line-height-search-form-empty:;                   /*搜索结果为空时的行高*/
--halo-search-widget-font-size-search-form-commands-item:;             /*搜索框底部快捷键提示字体大小*/
--halo-search-widget-line-height-search-commands-item:;                /*搜索框底部快捷键提示行高*/
--halo-search-widget-font-size-search-form-commands-item-kbd:;         /*搜索框底部快捷键提示图标大小*/ 
--halo-search-widget-min-width-search-commands-item-kbd:;              /*搜索框底部快捷键提示图标 min-wight*/
--halo-search-widget-font-family-search-form:;                         /*搜索框字体*/
```

2024-02-19 13:51 UTC, JohnNiang commented
/ping @halo-dev/sig-halo-console

2024-02-20 02:30 UTC, ruibaby requested changes

2024-02-20 02:30 UTC, ruibaby commented on packages/search-widget/src/search-form.ts
> +                  --halo-search-widget-color-form-input-bg,
看起来有格式问题，建议先 `cd packages/search-widget && pnpm prettier`

<img width="1535" alt="image" src="https://github.com/halo-dev/plugin-search-widget/assets/21301288/57da58d2-0741-46ba-8368-fe411f04b51d">

2024-02-20 09:46 UTC, ruibaby reviewed
/lgtm

2024-02-20 15:35 UTC, JohnNiang approved these changes
/approve

2024-02-20 15:36 UTC, merged